
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/SupabaseTypes';

const SUPABASE_URL = "https://nftakrzrazrxxmnxgryr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mdGFrcnpyYXpyeHhtbnhncnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTQ3MjUsImV4cCI6MjA1OTU3MDcyNX0.OFlCCnzHBNLuVT5QU9hKfBF6tyJsXC_8T3buUXqmDlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
